name             'elk-stack'
maintainer       'gm.murugan@gmail.com'
maintainer_email 'gmmurugan@gmail.com'
license          'MIT'
description      'Elastic Search + Kibana as a test backend'
long_description 'Elastic Search + Kibana as a test backend'
version          '1.0.0'

depends 'apt', '6.0.1'
depends 'java', '1.47.0'
depends 'elasticsearch', '3.0.4'
depends 'kibana5-gm', '1.6.0'
depends 'simple-logstash', '0.5.1'
depends 'runit', '~> 3.0.5'
